name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Aggiornato a ubuntu-latest per maggiore compatibilità

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Utilizzato per memorizzare nella cache le dipendenze con un timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Directory globale della cache di Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache locale Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Compila con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Carica artefatti
        uses: actions/upload-artifact@v4
        with:
          name: pacchetto
          path: ${{ steps.buildozer.outputs.filename }}
