name: Build Android APK (Metodo Kivy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Compilazione APK con Buildozer Action
        uses: kivy/action-android-buildozer@v1
        with:
          buildozer_version: 'stable'
          command: buildozer android debug

      - name: Caricamento dell'APK come Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pacchetto-apk
          path: bin/*.apk
